In [10]:
# import requests
# from bs4 import BeautifulSoup

# res=requests.get(f'https://www.daraz.com.np/mens-formal-bags/?spm=a2a0e.searchlist.cate_9_2.2.6e043034Wn7LZT','html.parser')
# data=res.text
# soup=BeautifulSoup(data,'lxml')
# # page=soup.find('title')
# # page
# container=soup.find('div',{'class':'ant-col-push-4 c1z9Ut'})
# container


# daraz ko scrapping

In [3]:
import requests
from bs4 import BeautifulSoup

total=[]
n=int(input("Enter page you want: "))
for page in range(1,n+1):
    res=requests.get(f'http://www.nepalstock.com/main/floorsheet/index/{page}/','html.parser')
    content=res.text
    soup=BeautifulSoup(content,'lxml')
    # tags=soup.table
    # tag=tags.get_text()
    # tag.split()
    # tag=tags.find_all('tr',align=False)
    # tag
    tags=soup.table
    tag=tags.find_all('tr',align=False)

    all_data=[]
    tag=tag[0:-2]
    #contents[0].get_text().split('\n')
    for j in tag:
        all_data.append(j.get_text())
    #all_data  it import in form like \n1\n2020051301000206\nADBL\n16\n45\n100\n347\n34700.00\n',  
    for k in range(len(all_data)):
        total.append(all_data[k][1:-1].split('\n'))
total

Enter page you want: 1

[['S.N.',
  'Contract No',
  'Stock Symbol',
  'Buyer Broker',
  'Seller Broker',
  'Quantity',
  'Rate',
  'Amount'],
 ['1', '2020051301000206', 'ADBL', '16', '45', '100', '347', '34700.00'],
 ['2', '2020051301000207', 'NABIL', '50', '58', '30', '660', '19800.00'],
 ['3', '2020051301000208', 'SICL', '44', '22', '10', '804', '8040.00'],
 ['4', '2020051301000209', 'STC', '1', '50', '10', '2352', '23520.00'],
 ['5', '2020051301000210', 'SICL', '44', '32', '10', '796', '7960.00'],
 ['6', '2020051301000211', 'BOKL', '7', '41', '20', '206', '4120.00'],
 ['7', '2020051301000197', 'FMDBL', '44', '34', '10', '407', '4070.00'],
 ['8', '2020051301000198', 'RMDC', '25', '50', '10', '562', '5620.00'],
 ['9', '2020051301000199', 'SBI', '45', '34', '20', '404', '8080.00'],
 ['10', '2020051301000200', 'GILB', '44', '19', '10', '1050', '10500.00'],
 ['11', '2020051301000201', 'HIDCL', '59', '36', '20', '124', '2480.00'],
 ['12', '2020051301000202', 'NTC', '13', '58', '310', '587', '181970.00'],
 ['13', '2020051301000203', 'NTC', '13', '32', '190', '587', '111530.00'],
 ['14', '2020051301000204', 'FMDBL', '44', '39', '10', '403', '4030.00'],
 ['15', '2020051301000205', 'NABIL', '36', '58', '20', '660', '13200.00'],
 ['16', '2020051301000190', 'DDBL', '44', '57', '10', '744', '7440.00'],
 ['17', '2020051301000191', 'NADEP', '55', '34', '10', '518', '5180.00'],
 ['18', '2020051301000192', 'JSLBB', '54', '5', '10', '1423', '14230.00'],
 ['19', '2020051301000193', 'DDBL', '44', '25', '10', '737', '7370.00'],
 ['20', '2020051301000194', 'SCB', '28', '32', '50', '556', '27800.00'],
 ['Page 1/11\xa012345678910Next›Last»']]

In [4]:
import csv

lenlist=len(total)
with open('pythonPrac1.csv','w+') as csvFile:
    for i in range(lenlist):
        w=csv.writer(csvFile)
        w.writerow(total[i])

In [2]:
import pandas as p

object=p.read_csv('pythonPrac1.csv',nrows=8)
object

,S.N.,Contract No,Stock Symbol,Buyer Broker,Seller Broker,Quantity,Rate,Amount
0,1,2020051301000206,ADBL,16,45,100,347,34700.0
1,2,2020051301000207,NABIL,50,58,30,660,19800.0
2,3,2020051301000208,SICL,44,22,10,804,8040.0
3,4,2020051301000209,STC,1,50,10,2352,23520.0
4,5,2020051301000210,SICL,44,32,10,796,7960.0
5,6,2020051301000211,BOKL,7,41,20,206,4120.0
6,7,2020051301000197,FMDBL,44,34,10,407,4070.0
7,8,2020051301000198,RMDC,25,50,10,562,5620.0

In [ ]:
from matplotlib import pyplot as plt